apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-orders-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-orders
  template:
    metadata:
      labels:
        app: customer-orders
    spec:
      nodeName: ip-172-31-27-120.us-east-2.compute.internal
      containers:
      - name: fastapi-app
        image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/rds-demo:avi-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: host
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: database
      - name: curl-sidecar
        image: curlimages/curl
        args:
        - /bin/sh
        - -c
        - while true; do curl -s http://localhost:8000; sleep 60; done
---
apiVersion: v1
kind: Service
metadata:
  name: customer-orders-service
  namespace: demo
  labels:
    app: customer-orders
spec:
  selector:
    app: customer-orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
