apiVersion: v1
kind: Namespace
metadata:
  name: multiple-errors-in-logs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiple-errors-in-logs-app
  namespace: multiple-errors-in-logs
  labels:
    app: multiple-errors-in-logs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiple-errors-in-logs-app
  template:
    metadata:
      labels:
        app: multiple-errors-in-logs-app
    spec:
      containers:
      - name: multiple-errors-in-logs-app
        image: multiple-errors-in-logs:latest
        imagePullPolicy: Always
        env:
        - name: MODEL
          value: "gpt-4"
        - name: TOKENS
          value: "100000"
        - name: INTERVAL
          value: "100"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always