apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-gen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-gen-app
  template:
    metadata:
      labels:
        app: curl-gen-app
    spec:
      containers:
      - name: curl-container
        image: curlimages/curl:7.78.0
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              echo "Checking endpoint http://meme-gen-service:5000...";
              curl -s http://meme-gen-service:5000 || echo "Failed to reach http://meme-gen-service:5000";
              sleep 30;
            done;
