apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processing-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processing-worker
  template:
    metadata:
      labels:
        app: payment-processing-worker
    spec:
      containers:
      - name: payment-processing-container
        image: bash
        env:
        - name: DEPLOY_ENV
          value: "Deployment.1.13"
        command: ["/bin/sh"]
        args: ["-c", "if [[ -z \"${DEPLOY_ENV}\" ]]; then echo Environment variable DEPLOY_ENV is undefined ; else while true; do echo hello; sleep 10;done; fi"]
