apiVersion: batch/v1
kind: Job
metadata:
  name: analytics-exporter
spec:
  ttlSecondsAfterFinished: 36000
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - 40Mi
        - "0"
        - 80Mi
        - "400"
        - "2"
        image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/memory-eater:1.0
        imagePullPolicy: Always
        name: memory-eater
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 100Mi
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/arch: amd64
