apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-relations-nginx
  labels:
    app: customer-relations-webapp
    environment: production
  annotations:
    description: "API service for managing customer data"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-relations-webapp
  template:
    metadata:
      labels:
        app: customer-relations-webapp
    spec:
      containers:
      - name: api-container
        image: nginx:1.14.2