kind: Namespace
apiVersion: v1
metadata:
  name: compare1
  labels:
    name: compare1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-app
  namespace: compare1
  labels:
    app: web-content
    function: delivery
spec:
  selector:
    matchLabels:
      app: web-content
  replicas: 1
  template:
    metadata:
      labels:
        app: web-content
    spec:
      containers:
      - name: content-server
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
kind: Namespace
apiVersion: v1
metadata:
  name: compare2
  labels:
    name: compare2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-app
  namespace: compare2
  labels:
    app: product-catalog
    function: listing
spec:
  selector:
    matchLabels:
      app: product-catalog
  replicas: 1
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
      - name: catalog-server
        image: nginx:1.13.0
        ports:
        - containerPort: 80
