apiVersion: v1
kind: Pod
metadata:
  name: inventory-management-api
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    command:
      - wge
      - "-O"
      - "/work-dir/index.html"
      - https://home.robusta.dev
