apiVersion: v1
kind: Pod
metadata:
  labels:
    app: analytics-worker
  name: analytics-worker
spec:
  containers:
  - image: busybox:1.28
    name: analytics-worker-container
    resources:
      requests:
        cpu: "600m"
    command: 
    - sleep
    - "1000"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "analytics"
    effect: "NoSchedule"
