apiVersion: v1
kind: Pod
metadata:
  labels:
    app: payment-processor
  name: payment-processor
spec:
  containers:
  - image: busybox:1.28
    name: payment-processor-container
    resources:
      requests:
        cpu: "600m"
    command: 
    - sleep
    - "1000"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "critical"
    effect: "NoSchedule"
  priorityClassName: high-priority
